### PR TITLE
change aws sdk v2

### PR DESCRIPTION
**Pull request by fukata**

### CODE REVIEW

**Comment by philipmw** [comment]
Looks good to me. Thanks for this.

Let's get one more ship-it from a collaborator, then we'll merge.

**Comment by fukata** [comment]
:+1:

**Comment by ngordon17** [comment]
Any idea when this will get pushed and published? I'd like to use the gem, but I need it to be compatible with the SDK V2.

**Comment by philipmw** [comment]
@ngordon17, I posted a PR to bump the gem version. I'll prod other collaborators to review and ship. Expect a new gem version tomorrow.

**Comment by philipmw** [comment]
@ngordon17, now I'm just waiting on permissions to rubygems.org from the package owner. I should get it in a couple of hours. Thanks for your patience.

**Comment by philipmw** [comment]
@ngordon17, I just released version 1.0.0 of the gem.

**Pull request merged**
