### PR TITLE
updated patch

### PR DESCRIPTION
**Pull request by ferdinandrosario**
updated patch for all ruby platform

### CODE REVIEW

**Comment by philipmw** [comment]
This is a good change, but we need to leave JRuby 1.7.11 because the biggest known consumer of this library uses it with JRuby 1.7.11. Also, rather than requiring a specific minor and patch version of JRuby and Rubinius, we can do "jruby-head" and "rbx-2".

**Comment by ferdinandrosario** [comment]
Ok. I updated this to encourage user to use latest patch. :smile:

**Comment by philipmw** [comment]
Did you forget to push the update?

**Comment by philipmw** [comment]
Closing.

**Pull request closed without merging**
